apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-slave-claim
spec:
  storageClassName: vsan-default-storage-policy
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
