apiVersion: v1
kind: Namespace
metadata:
  name: yelb
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: yelb
  labels:
    app: redis-server
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: redis-server
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-db
  namespace: yelb
  labels:
    app: yelb-db
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: yelb-db
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-appserver
  namespace: yelb
  labels:
    app: yelb-appserver
spec:
  type: ClusterIP
  ports:
  - port: 4567
  selector:
    app: yelb-appserver
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-ui
  namespace: yelb
  labels:
    app: yelb-ui
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: yelb-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-ui
  namespace: yelb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: yelb-ui
  template:
    metadata:
      labels:
        app: yelb-ui
    spec:
      containers:
      - name: yelb-ui
        image:  vmware/restreview-ui:V2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: yelb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - name: redis-server
        image: vmware/restreview-redis:V1
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-slave-data
          mountPath: /data
      volumes:
      - name: redis-slave-data
        persistentVolumeClaim:
          claimName: redis-slave-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-db
  namespace: yelb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: yelb-db
  template:
    metadata:
      labels:
        app: yelb-db
    spec:
      containers:
      - name: yelb-db
        image:  vmware/restreview-db:V1
        ports:
        - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-appserver
  namespace: yelb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: yelb-appserver
  template:
    metadata:
      labels:
        app: yelb-appserver
    spec:
      containers:
      - name: yelb-appserver
        image:  vmware/restreview-appserver:V2
        ports:
        - containerPort: 4567
---
apiVersion: networking.k8s.io/v1beta1 #using contour as ingress
kind: Ingress
metadata:
  name: yelb-ui-ingress
  namespace: yelb
  labels:
    app: yelb-ui-ingress
spec:
  rules:
    - host: yelb.platform.xyz
      http:
        paths:
        - backend:
            serviceName: yelb-ui
            servicePort: 80
